//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visibiliter
    {
        public int IdVisibiliter { get; set; }
        public int ProduitRef { get; set; }
        public System.DateTime DateVis { get; set; }
    
        public virtual Produits Produits { get; set; }
    }
}
